[run]
  timeout = "3m"
  skip-files = []
  skip-dirs = []

[linters-settings]

  [linters-settings.govet]
    check-shadowing = false

  [linters-settings.golint]
    min-confidence = 0.0

  [linters-settings.gocyclo]
    min-complexity = 12.0

  [linters-settings.maligned]
    suggest-new = true

  [linters-settings.goconst]
    min-len = 3.0
    min-occurrences = 4.0

  [linters-settings.misspell]
    locale = "US"

  [linters-settings.funlen]
    lines = 60 # default 60
    statements = 40 # default 40

[linters]
  enable-all = true
  disable = [
    "bodyclose",
    "goerr113",
    "nlreturn",
    "testpackage",
    "paralleltest",
    "tparallel",
  ]

[issues]
  exclude-use-default = false
  max-per-linter = 0
  max-same-issues = 0
  exclude = [
    "don't use an underscore in package name",
    "ST1003: should not use underscores in package names"
  ]

 [[issues.exclude-rules]]
    path = "(.+)_test.go"
    linters = ["goconst", "funlen", "godot", "scopelint"]